package com.forum.api.service.mybatis.model;

import java.util.Date;

public class SysAccount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account.user_id
     *
     * @mbg.generated Mon Sep 18 13:52:32 CST 2023
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account.user_name
     *
     * @mbg.generated Mon Sep 18 13:52:32 CST 2023
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account.user_role
     *
     * @mbg.generated Mon Sep 18 13:52:32 CST 2023
     */
    private String userRole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account.password_hash
     *
     * @mbg.generated Mon Sep 18 13:52:32 CST 2023
     */
    private String passwordHash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account.status
     *
     * @mbg.generated Mon Sep 18 13:52:32 CST 2023
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account.mail
     *
     * @mbg.generated Mon Sep 18 13:52:32 CST 2023
     */
    private String mail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account.error
     *
     * @mbg.generated Mon Sep 18 13:52:32 CST 2023
     */
    private Integer error;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account.enable_mark
     *
     * @mbg.generated Mon Sep 18 13:52:32 CST 2023
     */
    private String enableMark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account.crt_userid
     *
     * @mbg.generated Mon Sep 18 13:52:32 CST 2023
     */
    private String crtUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_account.crt_date
     *
     * @mbg.generated Mon Sep 18 13:52:32 CST 2023
     */
    private Date crtDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account.user_id
     *
     * @return the value of sys_account.user_id
     *
     * @mbg.generated Mon Sep 18 13:52:32 CST 2023
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account.user_id
     *
     * @param userId the value for sys_account.user_id
     *
     * @mbg.generated Mon Sep 18 13:52:32 CST 2023
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account.user_name
     *
     * @return the value of sys_account.user_name
     *
     * @mbg.generated Mon Sep 18 13:52:32 CST 2023
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account.user_name
     *
     * @param userName the value for sys_account.user_name
     *
     * @mbg.generated Mon Sep 18 13:52:32 CST 2023
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account.user_role
     *
     * @return the value of sys_account.user_role
     *
     * @mbg.generated Mon Sep 18 13:52:32 CST 2023
     */
    public String getUserRole() {
        return userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account.user_role
     *
     * @param userRole the value for sys_account.user_role
     *
     * @mbg.generated Mon Sep 18 13:52:32 CST 2023
     */
    public void setUserRole(String userRole) {
        this.userRole = userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account.password_hash
     *
     * @return the value of sys_account.password_hash
     *
     * @mbg.generated Mon Sep 18 13:52:32 CST 2023
     */
    public String getPasswordHash() {
        return passwordHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account.password_hash
     *
     * @param passwordHash the value for sys_account.password_hash
     *
     * @mbg.generated Mon Sep 18 13:52:32 CST 2023
     */
    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account.status
     *
     * @return the value of sys_account.status
     *
     * @mbg.generated Mon Sep 18 13:52:32 CST 2023
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account.status
     *
     * @param status the value for sys_account.status
     *
     * @mbg.generated Mon Sep 18 13:52:32 CST 2023
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account.mail
     *
     * @return the value of sys_account.mail
     *
     * @mbg.generated Mon Sep 18 13:52:32 CST 2023
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account.mail
     *
     * @param mail the value for sys_account.mail
     *
     * @mbg.generated Mon Sep 18 13:52:32 CST 2023
     */
    public void setMail(String mail) {
        this.mail = mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account.error
     *
     * @return the value of sys_account.error
     *
     * @mbg.generated Mon Sep 18 13:52:32 CST 2023
     */
    public Integer getError() {
        return error;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account.error
     *
     * @param error the value for sys_account.error
     *
     * @mbg.generated Mon Sep 18 13:52:32 CST 2023
     */
    public void setError(Integer error) {
        this.error = error;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account.enable_mark
     *
     * @return the value of sys_account.enable_mark
     *
     * @mbg.generated Mon Sep 18 13:52:32 CST 2023
     */
    public String getEnableMark() {
        return enableMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account.enable_mark
     *
     * @param enableMark the value for sys_account.enable_mark
     *
     * @mbg.generated Mon Sep 18 13:52:32 CST 2023
     */
    public void setEnableMark(String enableMark) {
        this.enableMark = enableMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account.crt_userid
     *
     * @return the value of sys_account.crt_userid
     *
     * @mbg.generated Mon Sep 18 13:52:32 CST 2023
     */
    public String getCrtUserid() {
        return crtUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account.crt_userid
     *
     * @param crtUserid the value for sys_account.crt_userid
     *
     * @mbg.generated Mon Sep 18 13:52:32 CST 2023
     */
    public void setCrtUserid(String crtUserid) {
        this.crtUserid = crtUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_account.crt_date
     *
     * @return the value of sys_account.crt_date
     *
     * @mbg.generated Mon Sep 18 13:52:32 CST 2023
     */
    public Date getCrtDate() {
        return crtDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_account.crt_date
     *
     * @param crtDate the value for sys_account.crt_date
     *
     * @mbg.generated Mon Sep 18 13:52:32 CST 2023
     */
    public void setCrtDate(Date crtDate) {
        this.crtDate = crtDate;
    }
}